import type { z } from "zod";
import type { ToolGroup } from "../server.js";

/**
 * Deliberately shallow Zod introspection: the reference needs only a type
 * label, required-ness, and description per parameter. In this Zod build the
 * `_def`/`.def` type tags are empty, so `constructor.name` is the stable
 * discriminator (verified: ZodString/ZodNumber/ZodBoolean/ZodArray/ZodEnum/
 * ZodRecord/ZodOptional). No descriptor uses `.default()`, so only optional/
 * nullable wrappers are unwrapped.
 */
function unwrap(schema: z.ZodTypeAny): z.ZodTypeAny {
  let current = schema;
  while (current.constructor.name === "ZodOptional" || current.constructor.name === "ZodNullable") {
    const inner = (current as unknown as { unwrap?: () => z.ZodTypeAny }).unwrap?.();
    if (!inner) break;
    current = inner;
  }
  return current;
}

function typeLabel(schema: z.ZodTypeAny): string {
  const inner = unwrap(schema);
  const name = inner.constructor.name;
  if (name === "ZodEnum") {
    const options = (inner as unknown as { options: readonly string[] }).options;
    // Escape the member separator so it does not close the Markdown table cell.
    return `enum(${options.join(" \\| ")})`;
  }
  const map: Record<string, string> = {
    ZodString: "string",
    ZodNumber: "number",
    ZodBoolean: "boolean",
    ZodArray: "array",
    ZodRecord: "object",
    ZodObject: "object",
    ZodUnknown: "any",
    ZodAny: "any",
  };
  return map[name] ?? name.replace(/^Zod/, "").toLowerCase();
}

/** Optional (or nullable/undefined-accepting) params parse `undefined` successfully. */
function isOptional(schema: z.ZodTypeAny): boolean {
  return schema.safeParse(undefined).success;
}

function descriptionOf(schema: z.ZodTypeAny): string {
  return schema.description ?? unwrap(schema).description ?? "";
}

/** Escapes the one Markdown-table-breaking character in free text. */
function escapeCell(text: string): string {
  return text.replace(/\|/g, "\\|");
}

function renderParams(shape: z.ZodRawShape): string {
  const keys = Object.keys(shape);
  if (keys.length === 0) return "_none_";
  return keys
    .map((key) => {
      // `z.ZodRawShape` types its values as the core `$ZodType` (fewer
      // members than the classic `ZodType` the runtime schemas actually
      // are - see the unwrap() doc comment), so re-assert to the classic
      // type the introspection helpers below are written against.
      const schema = shape[key] as unknown as z.ZodTypeAny;
      const required = isOptional(schema) ? "optional" : "required";
      const description = descriptionOf(schema);
      const suffix = description ? ` — ${escapeCell(description)}` : "";
      return `\`${key}\` ${typeLabel(schema)}, ${required}${suffix}`;
    })
    .join("<br>");
}

/**
 * Renders the full tool reference: one table per domain, one row per tool.
 * Deterministic (no dates, no ordering surprises) so the CI drift gate only
 * fires on a real descriptor change. The generator script runs this output
 * through Prettier before writing, so this need not pre-format the tables.
 */
export function renderToolDocs(groups: readonly ToolGroup[]): string {
  const lines: string[] = [
    "<!-- Generated by `npm run docs:tools`. Do not edit by hand. -->",
    "",
    "# Tool reference",
    "",
    "Every tool the server registers, grouped by domain in registration order. " +
      "Generated from the tool descriptors, so it always matches what ships. " +
      "Regenerate with `npm run docs:tools`.",
    "",
  ];
  for (const group of groups) {
    lines.push(`## ${group.title}`, "");
    lines.push("| Tool | Description | Parameters |");
    lines.push("| --- | --- | --- |");
    for (const tool of group.tools) {
      lines.push(
        `| \`${tool.name}\` | ${escapeCell(tool.description)} | ${renderParams(tool.inputSchema)} |`,
      );
    }
    lines.push("");
  }
  return lines.join("\n");
}
