import {
  cpSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";
import { z } from "zod";
import { createErrorResponse, type ErrorResponse } from "../errors.js";
import {
  assertInsideRoot,
  PathContainmentError,
  pathContainmentErrorResponse,
} from "../godot/paths.js";
import type { ToolDescriptor } from "../registry.js";
import { successResult } from "./result.js";

export interface OnboardingToolsDeps {
  /** MCP server version; also the bundled addon version (kept in lockstep). */
  serverVersion: string;
  /** Absolute path to the bundled addon source (server.resolveBundledAddonDir()). */
  bundledAddonDir: string;
}

/**
 * config/features version tag written into a scaffolded project.godot when the
 * caller does not pass one. Deliberately the FLOOR of the supported Godot
 * minors (AD-12): an older tag opens cleanly in a newer editor, whereas a
 * newer tag triggers a conversion prompt. Callers who know their editor
 * version should pass it explicitly (the onboarding integration test does).
 */
export const DEFAULT_SCAFFOLD_GODOT_VERSION = "4.4";

/** Standard Godot project subdirectories the scaffold lays down. */
const SCAFFOLD_DIRS = ["scenes", "scripts", "assets"] as const;

const MAIN_SCENE_TEMPLATE = `[gd_scene format=3]

[node name="Main" type="Node2D"]
`;

// Minimal, self-contained SVG so the only importable asset is trivial and
// warning-free. Any well-formed SVG imports as a texture in Godot 4.
const ICON_SVG_TEMPLATE = `<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" viewBox="0 0 128 128"><rect width="128" height="128" rx="24" fill="#478cbf"/></svg>
`;

/** Strips characters that would break the quoted value in project.godot. */
function sanitizeName(name: string): string {
  return name.replace(/["\r\n]/g, "").trim();
}

function projectGodotTemplate(name: string, godotVersion: string): string {
  return `; Engine configuration file.
; Generated by @cradial/godot-mcp create_project.

config_version=5

[application]

config/name="${name}"
config/features=PackedStringArray("${godotVersion}", "Forward Plus")
run/main_scene="res://scenes/main.tscn"
config/icon="res://icon.svg"
`;
}

/**
 * Rejects a target that already holds files. A missing folder is fine (we
 * create it); an empty folder is fine. A non-empty folder or a non-directory
 * is a precondition failure with its OWN guidance (NOT the no-editor error).
 */
function checkEmptyTarget(projectRoot: string): ErrorResponse | null {
  if (!existsSync(projectRoot)) return null;
  if (!statSync(projectRoot).isDirectory()) {
    return createErrorResponse({
      message: `Target "${projectRoot}" already exists and is not a directory.`,
      possibleSolutions: ["Pass a path to an empty folder or a folder that does not exist yet."],
    });
  }
  if (readdirSync(projectRoot).length > 0) {
    return createErrorResponse({
      message: `Target directory "${projectRoot}" is not empty; refusing to scaffold over existing files.`,
      possibleSolutions: [
        "Choose an empty or not-yet-existing folder for the new project.",
        "To add the bridge addon to an EXISTING project, use install_addon instead.",
      ],
    });
  }
  return null;
}

/** Reads `version="..."` out of a plugin.cfg, or null when the file is absent. */
function readPluginVersion(pluginCfgPath: string): string | null {
  if (!existsSync(pluginCfgPath)) return null;
  return /version="([^"]+)"/.exec(readFileSync(pluginCfgPath, "utf8"))?.[1] ?? null;
}

export function createOnboardingTools(deps: OnboardingToolsDeps): ToolDescriptor[] {
  const createProject: ToolDescriptor = {
    name: "create_project",
    description:
      "Scaffold a new Godot 4 project (project.godot, icon, main scene, standard folders) in an empty or new folder.",
    inputSchema: {
      project_path: z
        .string()
        .min(1, "project_path must not be empty.")
        .describe(
          "Absolute path to an empty or not-yet-existing folder for the new Godot project.",
        ),
      project_name: z
        .string()
        .min(1)
        .optional()
        .describe("Human-readable project name; defaults to the target folder name."),
      godot_version: z
        .string()
        .regex(/^\d+\.\d+$/, 'godot_version must look like "4.4".')
        .optional()
        .describe(
          'Godot minor to tag config/features with (e.g. "4.4"); defaults to a safe floor.',
        ),
    },
    handler: async (args) => {
      const { project_path, project_name, godot_version } = args as {
        project_path: string;
        project_name?: string;
        godot_version?: string;
      };

      if (!path.isAbsolute(project_path)) {
        return createErrorResponse({
          message: `project_path "${project_path}" must be an absolute path.`,
          possibleSolutions: [
            "Pass the absolute path to the folder the new project should live in.",
          ],
        });
      }

      const projectRoot = path.resolve(project_path);
      const precondition = checkEmptyTarget(projectRoot);
      if (precondition) return precondition;

      const projectName =
        sanitizeName(project_name ?? path.basename(projectRoot)) || "Untitled Project";
      const godotVersion = godot_version ?? DEFAULT_SCAFFOLD_GODOT_VERSION;

      mkdirSync(projectRoot, { recursive: true });

      const createdFiles: string[] = [];
      try {
        for (const dir of SCAFFOLD_DIRS) {
          mkdirSync(assertInsideRoot(projectRoot, dir), { recursive: true });
        }
        const files: Array<[string, string]> = [
          ["project.godot", projectGodotTemplate(projectName, godotVersion)],
          ["icon.svg", ICON_SVG_TEMPLATE],
          [path.join("scenes", "main.tscn"), MAIN_SCENE_TEMPLATE],
        ];
        for (const [rel, contents] of files) {
          writeFileSync(assertInsideRoot(projectRoot, rel), contents, "utf8");
          createdFiles.push(rel.split(path.sep).join("/"));
        }
      } catch (error) {
        if (error instanceof PathContainmentError) return pathContainmentErrorResponse(error);
        throw error;
      }

      return successResult("Created Godot project", {
        project_path: projectRoot,
        project_name: projectName,
        godot_version: godotVersion,
        main_scene: "res://scenes/main.tscn",
        created_files: createdFiles,
        next_steps: [
          "Install the bridge addon into this project with install_addon.",
          "Open the project in the Godot editor.",
          "Enable 'Godot MCP' under Project > Project Settings > Plugins.",
        ],
      });
    },
  };

  const installAddon: ToolDescriptor = {
    name: "install_addon",
    description:
      "Install or update the Godot MCP bridge addon into an existing project, then report the enable steps.",
    inputSchema: {
      project_path: z
        .string()
        .min(1, "project_path must not be empty.")
        .describe(
          "Absolute path to an existing Godot project directory (containing project.godot).",
        ),
    },
    handler: async (args) => {
      const { project_path } = args as { project_path: string };

      if (!path.isAbsolute(project_path)) {
        return createErrorResponse({
          message: `project_path "${project_path}" must be an absolute path.`,
          possibleSolutions: [
            "Pass the absolute path to the project folder that contains project.godot.",
          ],
        });
      }

      const projectRoot = path.resolve(project_path);
      if (!existsSync(path.join(projectRoot, "project.godot"))) {
        return createErrorResponse({
          message: `No project.godot found in "${projectRoot}"; it is not a Godot project.`,
          possibleSolutions: [
            "Pass the folder that directly contains project.godot.",
            "Starting from an empty folder? Run create_project first, then install_addon.",
          ],
        });
      }

      let destination: string;
      try {
        destination = assertInsideRoot(projectRoot, path.join("addons", "godot_mcp"));
      } catch (error) {
        if (error instanceof PathContainmentError) return pathContainmentErrorResponse(error);
        throw error;
      }

      const previousVersion = readPluginVersion(path.join(destination, "plugin.cfg"));
      mkdirSync(path.dirname(destination), { recursive: true });
      cpSync(deps.bundledAddonDir, destination, { recursive: true });
      const installedVersion =
        readPluginVersion(path.join(deps.bundledAddonDir, "plugin.cfg")) ?? deps.serverVersion;

      return successResult(
        previousVersion ? "Updated Godot MCP addon" : "Installed Godot MCP addon",
        {
          project_path: projectRoot,
          action: previousVersion ? "updated" : "installed",
          installed_version: installedVersion,
          previous_version: previousVersion,
          addon_path: "res://addons/godot_mcp",
          enable_steps: [
            "Open the project in the Godot editor (or restart it if already open).",
            "Enable 'Godot MCP' under Project > Project Settings > Plugins.",
            "The bridge starts automatically once enabled; confirm with bridge_status.",
          ],
        },
      );
    },
  };

  return [createProject, installAddon];
}
